server:
  port: 9001
spring:
  application:
    name: twesqu_base
  datasource:
    url: jdbc:mysql://localhost:3307/twesqu_data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true